New Persistent/CloudKit Data Scheme
tweetnest/TweetNest pull request #19
Opened 2022-05-04 01:42 UTC by sinoru

2022-05-09 11:14 UTC, minacle requested changes

2022-05-09 11:14 UTC, minacle commented on TweetNestKit/CoreDataStack/ManagedObjects/ManagedUserDetail+CoreDataProperties.swift
> +        return NSFetchRequest<ManagedUserDetail>(entityName: "UserDetail")
단일 반환 함수이니 `return` 문은 필요하지 않습니다.

타입을 명시적으로 중복하는 것은 피합시다. 대신 아래의 코드를 사용합시다.

```swift
.init(entityName: "UserDetail")
```

2022-05-09 11:14 UTC, minacle commented on TweetNestKit/CoreDataStack/ManagedObjects/ManagedUser+CoreDataProperties.swift
> +        return NSFetchRequest<ManagedUser>(entityName: "User")
단일 반환 함수이니 `return` 문은 필요하지 않습니다.

타입을 명시적으로 중복하는 것은 피합시다. 대신 아래의 코드를 사용합시다.

```swift
.init(entityName: "User")
```

2022-05-09 11:14 UTC, minacle commented on TweetNestKit/CoreDataStack/PersistentContainer+Supports.swift
> +            NSSortDescriptor(key: "creationDate", ascending: true),
왜 이 파일에서만 keyPath 가 아니라 key 를 씁니까?

2022-05-09 11:14 UTC, minacle commented on TweetNestKit/SecureUnarchiveFromDataTransformer.swift
> +@objc
_NSSecureUnarchiveFromDataTransformer_ 클래스는 _NSObject_ 클래스를 상속하는 Objective-C 클래스입니다. 해당 클래스의 서브클래스를 만들 때 명시적인 `@objc` 어트리뷰트는 필요하지 않습니다.

2022-05-09 11:17 UTC, sinoru commented on TweetNestKit/CoreDataStack/ManagedObjects/ManagedUserDetail+CoreDataProperties.swift
> +        return NSFetchRequest<ManagedUserDetail>(entityName: "UserDetail")
Xcode 자동 생성 코드입니다 (...)

수정하면 매번 생성할때마다 다시 수정해야할 것 같아서... 좀 의미없는 수정이 될 것 같네요.

2022-05-09 11:17 UTC, sinoru commented on TweetNestKit/CoreDataStack/ManagedObjects/ManagedUser+CoreDataProperties.swift
> +        return NSFetchRequest<ManagedUser>(entityName: "User")
Xcode 자동 생성 코드입니다 (...)

수정하면 매번 생성할때마다 다시 수정해야할 것 같아서... 좀 의미없는 수정이 될 것 같네요.

2022-05-09 11:18 UTC, sinoru commented on TweetNestKit/CoreDataStack/PersistentContainer+Supports.swift
> +            NSSortDescriptor(key: "creationDate", ascending: true),
PersistentContainer+V1으로 이동한 코드의 잔재네요. (중복) 일단 V1은 일단 기존 모델이 사라져서 직접 key로 호출해야하는건 맞습니다.

해당 코드는 제거하도록 하겠습니다.

2022-05-12 10:46 UTC, minacle requested changes
기존 데이터 모델의 버전을 갱신하지 않고 새 데이터 모델을 만드는 식으로 작업하는 이유가 있나요? 매핑 모델을 사용하면 이렇게 번거로운 작업을 하지 않아도 될 것 같습니다만.

2022-05-12 10:46 UTC, minacle commented on TweetNestKit/CoreDataStack/TweetNestKitV3.xcdatamodeld/TweetNestKitV3.xcdatamodel/contents
> +        <attribute name="modificationDate" optional="YES" attributeType="Date" usesScalarValueType="NO"/>
`modificationDate` 어트리뷰트는 다른 코드에서 사용하지 않기로 하였지만 데이터 모델에는 아직 남아 있습니다.

2022-05-12 10:46 UTC, minacle commented on TweetNestKit/CoreDataStack/ManagedObjects/ManagedUser+CoreDataProperties.swift
> +    @NSManaged public var modificationDate: Date?
`modificationDate` 어트리뷰트는 다른 코드에서 사용하지 않기로 하였지만 관리 개체 선언에는 아직 남아 있습니다.

2022-05-12 10:46 UTC, minacle commented on TweetNestKit/CoreDataStack/ManagedObjects/ManagedUser+CoreDataProperties.swift
> +    @NSManaged public var modificationDate: Date?
`modificationDate` 어트리뷰트는 다른 코드에서 사용하지 않기로 하였지만 데이터 모델에는 아직 남아 있습니다.

2022-05-12 10:46 UTC, minacle commented on TweetNestKit/CoreDataStack/PersistentContainer+Migration.swift
> +    func migrationIfNeeded() throws {
해당 메소드의 이름은 `migrateIfNeeded` 또는 `doMigrationIfNeeded` 가 더 적절할 것 같습니다.

2022-05-12 10:46 UTC, minacle commented on TweetNestKit/CoreDataStack/PersistentContainer+Migration.swift
> +    func migrationIfNeeded() throws {
해당 메소드의 이름은 `migrateIfNeeded` 또는 `doMigrationIfNeeded` 가 더 적절할 것 같습니다.

2022-05-12 10:52 UTC, sinoru commented on TweetNestKit/CoreDataStack/PersistentContainer+Migration.swift
> +    func migrationIfNeeded() throws {
이 예시를 볼때 해당 메소드명도 괜찮지 않나 생각이 듭니다. (https://developer.apple.com/documentation/uikit/uiviewcontroller/1621446-loadviewifneeded)

2022-05-12 10:53 UTC, sinoru commented
> 기존 데이터 모델의 버전을 갱신하지 않고 새 데이터 모델을 만드는 식으로 작업하는 이유가 있나요? 매핑 모델을 사용하면 이렇게 번거로운 작업을 하지 않아도 될 것 같습니다만.

같은 Store간 Migration 일 때만 모델 맵핑이 가능해서 이렇게 수정한 부분도 있고, CloudKit도 기존 모델에서 크게 변화할 경우 필드 삭제 등이 불가능하여 이렇게 선택한 배경이 있습니다.

2022-05-12 10:56 UTC, minacle commented on TweetNestKit/CoreDataStack/PersistentContainer+Migration.swift
> +    func migrationIfNeeded() throws {
괜찮지 않나 생각이 들지 않습니다. 예시의 load 또한 동사로서 사용되었습니다.

2022-05-12 12:15 UTC, minacle approved these changes

2022-05-12 12:25 UTC, merged