Implement previews + helpers
tweetnest/TweetNest pull request #21
Opened 2022-05-19 11:43 UTC by minacle

2022-05-19 11:47 UTC, minacle commented on TweetNest/Shared/AppSidebarAccountsSections.swift
>  }
이 미리보기 제공자를 `#if DEBUG` 로 감싸지 않았습니다.

2022-05-20 10:22 UTC, sinoru requested changes

2022-05-20 10:22 UTC, sinoru commented on TweetNest/Shared/AppSidebarAccountsSections+Section.swift
> + struct AppSidebarAccountsSections_Section_Previews: PreviewProvider {
Lint 룰을 수정하거나 `_Previews` 앞의 `_`를 제거해야할 것 같습니다.

2022-05-20 10:22 UTC, sinoru commented on TweetNest/Shared/Extensions/TweetNestKit/ManagedAccount+Preview.swift
> +        }
Lint

2022-05-20 10:22 UTC, sinoru commented on TweetNest/Shared/Extensions/TweetNestKit/Session+Preview.swift
>          }
Lint

2022-05-20 10:22 UTC, sinoru commented on TweetNest/Shared/UserView+AllDataView.swift
> +struct UserView_AllDataView_Previews: PreviewProvider {
Lint 룰을 수정하거나 `_Previews` 앞의 `_`를 제거해야할 것 같습니다.

2022-05-20 10:22 UTC, sinoru commented on TweetNest/Shared/UserView+FootnotesView.swift
> +struct UserView_FootnotesView_Preview: PreviewProvider {
Lint 룰을 수정하거나 `_Previews` 앞의 `_`를 제거해야할 것 같습니다.

2022-05-20 12:02 UTC, sinoru commented
SwiftLint 룰을 변경하였으니(9a61f635), merge나 rebase 부탁드립니다. 🙏

2022-05-21 04:08 UTC, merged