Fix + Implement copying behaviours
tweetnest/TweetNest pull request #22
Opened 2022-05-19 22:41 UTC by minacle

2022-05-21 06:24 UTC, sinoru commented on TweetNest/Shared/GlobalFunctions.swift
> +// MARK: - copyToPasteboard(_:content:)
펑션을 너무 글로벌 스코프로 뺀거 아닌가 우려가 조금 들고,
"GlobalFunctions" 파일이면 너무 광범위한거 같습니다.

2022-05-21 14:55 UTC, sinoru requested changes

2022-05-21 14:55 UTC, sinoru commented on TweetNest/Shared/Pasteboard.swift
> +#else
compile-time 체크를 위해 기타 플랫폼에서 해당 class의 availbility를 조절하는게 좋을 것 같습니다.

2022-05-21 14:55 UTC, sinoru commented on TweetNest/Shared/Pasteboard.swift
> +extension Pasteboard: _ObjectiveCBridgeable {
`_ObjectiveCBridgeable`는 사용하지 않는게 좋을 것 같습니다. https://github.com/apple/swift-evolution/blob/master/proposals/0058-objectivecbridgeable.md#rationale

2022-05-21 14:55 UTC, sinoru commented on TweetNest/Shared/Pasteboard.swift
> +extension Pasteboard: _ObjectiveCBridgeable {
`_ObjectiveCBridgeable`는 사용하지 않는게 좋을 것 같습니다. https://github.com/apple/swift-evolution/blob/master/proposals/0058-objectivecbridgeable.md#rationale

2022-05-21 14:58 UTC, minacle commented on TweetNest/Shared/Pasteboard.swift
> +#else
해당 클래스는 이미 availability가 지정되어 있습니다. 컴파일러를 개변하지 않고는 이하 코드에 접근할 수 없습니다.

2022-05-21 15:02 UTC, sinoru commented on TweetNest/Shared/Pasteboard.swift
> +#else
그렇다면 `#else` 아래는 죽은 코드 같아서... 이걸 앞에서 #if 처리를 해서 빠지지 않도록 하거나 등의 작업이 필요할 것 같습니다.

2022-05-21 15:07 UTC, minacle commented on TweetNest/Shared/Pasteboard.swift
> +#else
해당 부분을 삭제하면 프로토콜을 만족하지 못하여 빌드할 수 없습니다.

2022-05-21 15:36 UTC, sinoru commented on TweetNest/Shared/UserDetailProfileView.swift
> +                                #endif
요걸 없애고 아래 코드로 통합하는게 좋을 것 같습니다.

(저번 리뷰때 미처 놓쳤네요 🙏)

2022-05-22 16:01 UTC, sinoru approved these changes
LGTM

2022-05-22 16:01 UTC, merged